title: Jekyll Bootstrap Theme
author:
  name: 'Pete Olsen III'
  email: 'pete@hepaestus.com'
description: >- # this means to ignore newlines until next element
  Awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "xp8r.com"
excerpts:
  # Displays or hides post excerpts from home layout post listing.
  show: true
  # Cuts off excerpts with an ellipsis (...) after 32 words (approx. 2 lines).
  # You can also leave this false, and manually control excerpt length:
  # https://jekyllrb.com/docs/posts/#post-excerpts
  truncate: false    
date: 2024-09-14 17:53:00 +0900
date_format: "%y-%m-%d %H:%M:%S %z"
iso_date_format: "%Y-%m-%dT%H:%M:%S%:z"
search_enabled: true
git_build_data_color: '#eee'
google_analytics: false
google_tag_manager: 'GTM-XXXXXXX'
sidebar_headers: true
show_top_link: true
formspree_id: 'your_formspree_id'

# Theme configuration
bootstrap:
  # Theme date format
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %-d, %Y"
  # If you want to link only specific pages in your header, uncomment
  # this and add the path to the page *files* in order as they should show up
  header_pages:
   - about.md

  # generate social links in footer
  social_links:
    #twitter: 'https://twitter.com/jonaharagon'
    github:  'https://github.com/dj-chris-hale'
    #facebook: 'https://example.com/@jekyllrb'
    instagram: 'https://instagram.com/djchrishale'
    #linkedin: 'https://example.com/@jekyllrb'
    #google: 'https://example.com/@jekyllrb'
    youtube: 'https://example.com/djchrishale'
    #twitch: 'https://example.com/@jekyllrb'
    #telegram: 'https://example.com/@jekyllrb'
    #whatsapp: 'https://example.com/@jekyllrb'
    #discord: 'https://example.com/@jekyllrb'
    #slack: 'https://example.com/@jekyllrb'

# Tags Cloud
tags_cloud: true

collections:
  posts_tags:
    permalink: /tags/:name/
    output: true
defaults:
  - scope:
      path: ''
      type: posts_tags
    values:
      permalink: "/tags/:name/"
      layout: tags

# Build settings
# theme: 

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sass-converter

include: 
  - /_posts_tags/_site_tags_missing.txt
  - /assets/js/documents.js
  - /assets/css/styles.css

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .vscode
  - .git
  - .gitignore
  - .gitmodules
  - .gitattributes
  - .editorconfig
  - yarn.lock
  - package.json
  - package-lock.json
  - README.md
